name: dowplay
description: DowPlay plugin project.
version: 0.0.3
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.dowplay.dowplay
        pluginClass: DowplayPlugin
      ios:
        pluginClass: DowplayPlugin
      linux:
        pluginClass: DowplayPlugin
      macos:
        pluginClass: DowplayPlugin
      windows:
        pluginClass: DowplayPluginCApi
